coverage:
  status:
    project:
      default:
        target: 60%
    patch:
      default:
        target: 60%
    UnitTests:
      default:
        target: 0%
    IntegrationTests:
      default:
        target: 60%

flags:
  UnitTests:
    carryforward: true
  IntegrationTests:
    carryforward: true

comment:
  layout: " diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false

