# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  pull-requests: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Unit Tests
        run: dotnet test Blogplace.Tests.Unit /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      - name: Codecov Unit
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./Blogplace.Tests.Unit/coverage.opencover.xml
          flags: UnitTests
          fail_ci_if_error: true
      - name: Integration Tests
        run: dotnet test Blogplace.Tests.Integration /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      - name: Codecov Integration
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./Blogplace.Tests.Integration/coverage.opencover.xml
          flags: IntegrationTests
          fail_ci_if_error: true
